/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_test_x.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: victor <victor.horel@learner.42.tech>      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/14 18:29:33 by victor            #+#    #+#             */
/*   Updated: 2026/05/16 08:43:49 by victor           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_tester.h"

void	ft_test_x(void)
{
	int				count;
	unsigned int	xnbr;
	
	count = 0;
	xnbr = 0xFFFF;

	count += ft_tester('x', "%x", xnbr);
	count += ft_tester('x', "%x", 0u);
	count += ft_tester('x', "%x", 1u);
	count += ft_tester('x', "%x", 9u);
	count += ft_tester('x', "%x", 10u);
	count += ft_tester('x', "%x", 15u);
	count += ft_tester('x', "%x", 16u);
	count += ft_tester('x', "%x", 42u);
	count += ft_tester('x', "%x", 255u);
	count += ft_tester('x', "%x", UINT_MAX);
	count += ft_tester('x', "%1x", xnbr);
	count += ft_tester('x', "%2x", xnbr);
	count += ft_tester('x', "%3x", xnbr);
	count += ft_tester('x', "%5x", xnbr);
	count += ft_tester('x', "%10x", xnbr);
	count += ft_tester('x', "%20x", xnbr);
	count += ft_tester('x', "%1x", 0u);
	count += ft_tester('x', "%5x", 0u);
	count += ft_tester('x', "%10x", 0u);
	count += ft_tester('x', "%20x", UINT_MAX);
	count += ft_tester('x', "%-1x", xnbr);
	count += ft_tester('x', "%-2x", xnbr);
	count += ft_tester('x', "%-5x", xnbr);
	count += ft_tester('x', "%-10x", xnbr);
	count += ft_tester('x', "%-20x", xnbr);
	count += ft_tester('x', "%-5x", 0u);
	count += ft_tester('x', "%-10x", 0u);
	count += ft_tester('x', "%-20x", UINT_MAX);
	count += ft_tester('x', "%01x", xnbr);
	count += ft_tester('x', "%02x", xnbr);
	count += ft_tester('x', "%03x", xnbr);
	count += ft_tester('x', "%05x", xnbr);
	count += ft_tester('x', "%010x", xnbr);
	count += ft_tester('x', "%020x", xnbr);
	count += ft_tester('x', "%05x", 0u);
	count += ft_tester('x', "%010x", 0u);
	count += ft_tester('x', "%020x", UINT_MAX);
	count += ft_tester('x', "%-01x", xnbr);
	count += ft_tester('x', "%-02x", xnbr);
	count += ft_tester('x', "%-05x", xnbr);
	count += ft_tester('x', "%-010x", xnbr);
	count += ft_tester('x', "%-020x", xnbr);
	count += ft_tester('x', "%-05x", 0u);
	count += ft_tester('x', "%-010x", 0u);
	count += ft_tester('x', "%-020x", UINT_MAX);
	count += ft_tester('x', "%--1x", xnbr);
	count += ft_tester('x', "%--5x", xnbr);
	count += ft_tester('x', "%---5x", xnbr);
	count += ft_tester('x', "%----10x", xnbr);
	count += ft_tester('x', "%0001x", xnbr);
	count += ft_tester('x', "%0005x", xnbr);
	count += ft_tester('x', "%00010x", xnbr);
	count += ft_tester('x', "%0005x", 0u);
	count += ft_tester('x', "%--005x", xnbr);
	count += ft_tester('x', "%-0-05x", xnbr);
	count += ft_tester('x', "%.0x", 0u);
	count += ft_tester('x', "%.0x", xnbr);
	count += ft_tester('x', "%.1x", 0u);
	count += ft_tester('x', "%.1x", xnbr);
	count += ft_tester('x', "%.2x", xnbr);
	count += ft_tester('x', "%.3x", xnbr);
	count += ft_tester('x', "%.5x", xnbr);
	count += ft_tester('x', "%.10x", xnbr);
	count += ft_tester('x', "%.20x", xnbr);
	count += ft_tester('x', "%.20x", UINT_MAX);
	count += ft_tester('x', "%1.0x", 0u);
	count += ft_tester('x', "%1.0x", xnbr);
	count += ft_tester('x', "%5.0x", 0u);
	count += ft_tester('x', "%5.0x", xnbr);
	count += ft_tester('x', "%5.1x", xnbr);
	count += ft_tester('x', "%5.3x", xnbr);
	count += ft_tester('x', "%5.5x", xnbr);
	count += ft_tester('x', "%5.10x", xnbr);
	count += ft_tester('x', "%8.5x", xnbr);
	count += ft_tester('x', "%10.5x", xnbr);
	count += ft_tester('x', "%20.10x", xnbr);
	count += ft_tester('x', "%25.20x", UINT_MAX);
	count += ft_tester('x', "%-1.0x", 0u);
	count += ft_tester('x', "%-1.0x", xnbr);
	count += ft_tester('x', "%-5.0x", 0u);
	count += ft_tester('x', "%-5.0x", xnbr);
	count += ft_tester('x', "%-5.3x", xnbr);
	count += ft_tester('x', "%-8.5x", xnbr);
	count += ft_tester('x', "%-10.5x", xnbr);
	count += ft_tester('x', "%-20.10x", xnbr);
	count += ft_tester('x', "%-25.20x", UINT_MAX);
	count += ft_tester('x', "%01.0x", 0u);
	count += ft_tester('x', "%05.0x", 0u);
	count += ft_tester('x', "%010.0x", 0u);
	count += ft_tester('x', "%05.0x", xnbr);
	count += ft_tester('x', "%05.3x", xnbr);
	count += ft_tester('x', "%08.5x", xnbr);
	count += ft_tester('x', "%010.5x", xnbr);
	count += ft_tester('x', "%020.10x", UINT_MAX);
	count += ft_tester('x', "%#x", xnbr);
	count += ft_tester('x', "%#x", 0u);
	count += ft_tester('x', "%#x", 1u);
	count += ft_tester('x', "%#x", 15u);
	count += ft_tester('x', "%#x", 16u);
	count += ft_tester('x', "%#x", 255u);
	count += ft_tester('x', "%#x", UINT_MAX);
	count += ft_tester('x', "%#1x", xnbr);
	count += ft_tester('x', "%#2x", xnbr);
	count += ft_tester('x', "%#5x", xnbr);
	count += ft_tester('x', "%#10x", xnbr);
	count += ft_tester('x', "%#20x", xnbr);
	count += ft_tester('x', "%#5x", 0u);
	count += ft_tester('x', "%#10x", 0u);
	count += ft_tester('x', "%#20x", UINT_MAX);
	count += ft_tester('x', "%#-1x", xnbr);
	count += ft_tester('x', "%#-5x", xnbr);
	count += ft_tester('x', "%#-10x", xnbr);
	count += ft_tester('x', "%#-20x", xnbr);
	count += ft_tester('x', "%-#1x", xnbr);
	count += ft_tester('x', "%-#5x", xnbr);
	count += ft_tester('x', "%-#10x", xnbr);
	count += ft_tester('x', "%-#20x", xnbr);
	count += ft_tester('x', "%#-10x", 0u);
	count += ft_tester('x', "%#-20x", UINT_MAX);
	count += ft_tester('x', "%#01x", xnbr);
	count += ft_tester('x', "%#02x", xnbr);
	count += ft_tester('x', "%#05x", xnbr);
	count += ft_tester('x', "%#010x", xnbr);
	count += ft_tester('x', "%#020x", xnbr);
	count += ft_tester('x', "%#05x", 0u);
	count += ft_tester('x', "%#010x", 0u);
	count += ft_tester('x', "%#020x", UINT_MAX);
	count += ft_tester('x', "%#.0x", 0u);
	count += ft_tester('x', "%#.0x", xnbr);
	count += ft_tester('x', "%#.1x", 0u);
	count += ft_tester('x', "%#.1x", xnbr);
	count += ft_tester('x', "%#.3x", xnbr);
	count += ft_tester('x', "%#.5x", xnbr);
	count += ft_tester('x', "%#.10x", xnbr);
	count += ft_tester('x', "%#.20x", UINT_MAX);
	count += ft_tester('x', "%#5.0x", 0u);
	count += ft_tester('x', "%#5.0x", xnbr);
	count += ft_tester('x', "%#5.3x", xnbr);
	count += ft_tester('x', "%#8.5x", xnbr);
	count += ft_tester('x', "%#10.5x", xnbr);
	count += ft_tester('x', "%#20.10x", xnbr);
	count += ft_tester('x', "%#25.20x", UINT_MAX);
	count += ft_tester('x', "%#05.0x", 0u);
	count += ft_tester('x', "%#05.0x", xnbr);
	count += ft_tester('x', "%#05.3x", xnbr);
	count += ft_tester('x', "%#08.5x", xnbr);
	count += ft_tester('x', "%#010.5x", xnbr);
	count += ft_tester('x', "%#020.10x", UINT_MAX);
	count += ft_tester('x', "%*x", 0, xnbr);
	count += ft_tester('x', "%*x", 1, xnbr);
	count += ft_tester('x', "%*x", 2, xnbr);
	count += ft_tester('x', "%*x", 5, xnbr);
	count += ft_tester('x', "%*x", 10, xnbr);
	count += ft_tester('x', "%*x", 20, xnbr);
	count += ft_tester('x', "%*x", -1, xnbr);
	count += ft_tester('x', "%*x", -2, xnbr);
	count += ft_tester('x', "%*x", -5, xnbr);
	count += ft_tester('x', "%*x", -10, xnbr);
	count += ft_tester('x', "%*x", -20, xnbr);
	count += ft_tester('x', "%*x", 5, 0u);
	count += ft_tester('x', "%*x", -5, 0u);
	count += ft_tester('x', "%*x", 20, UINT_MAX);
	count += ft_tester('x', "%*x", -20, UINT_MAX);
	count += ft_tester('x', "%.*x", 0, 0u);
	count += ft_tester('x', "%.*x", 0, xnbr);
	count += ft_tester('x', "%.*x", 1, 0u);
	count += ft_tester('x', "%.*x", 1, xnbr);
	count += ft_tester('x', "%.*x", 3, xnbr);
	count += ft_tester('x', "%.*x", 5, xnbr);
	count += ft_tester('x', "%.*x", 10, xnbr);
	count += ft_tester('x', "%.*x", 20, xnbr);
	count += ft_tester('x', "%.*x", -1, xnbr);
	count += ft_tester('x', "%.*x", -5, xnbr);
	count += ft_tester('x', "%.*x", -10, xnbr);
	count += ft_tester('x', "%*.*x", 0, 0, 0u);
	count += ft_tester('x', "%*.*x", 0, 5, xnbr);
	count += ft_tester('x', "%*.*x", 5, 0, 0u);
	count += ft_tester('x', "%*.*x", 5, 0, xnbr);
	count += ft_tester('x', "%*.*x", 8, 5, xnbr);
	count += ft_tester('x', "%*.*x", 10, 5, xnbr);
	count += ft_tester('x', "%*.*x", 20, 10, UINT_MAX);
	count += ft_tester('x', "%*.*x", -8, 5, xnbr);
	count += ft_tester('x', "%*.*x", -10, 5, xnbr);
	count += ft_tester('x', "%*.*x", -20, 10, UINT_MAX);
	count += ft_tester('x', "%*.*x", 8, -5, xnbr);
	count += ft_tester('x', "%*.*x", -8, -5, xnbr);
	count += ft_tester('x', "%0*x", 5, xnbr);
	count += ft_tester('x', "%0*x", -5, xnbr);
	count += ft_tester('x', "%0*x", 5, 0u);
	count += ft_tester('x', "%0*x", -5, 0u);
	count += ft_tester('x', "%-*x", 5, xnbr);
	count += ft_tester('x', "%-*x", -5, xnbr);
	count += ft_tester('x', "%-*x", 5, 0u);
	count += ft_tester('x', "%-*x", -5, 0u);
	count += ft_tester('x', "%#*x", 8, xnbr);
	count += ft_tester('x', "%#*x", -8, xnbr);
	count += ft_tester('x', "%#*x", 8, 0u);
	count += ft_tester('x', "%#*x", -8, 0u);
	count += ft_tester('x', "%0.*x", 5, xnbr);
	count += ft_tester('x', "%0.*x", -5, xnbr);
	count += ft_tester('x', "%-.*x", 5, xnbr);
	count += ft_tester('x', "%-.*x", -5, xnbr);
	count += ft_tester('x', "%#.*x", 0, 0u);
	count += ft_tester('x', "%#.*x", 0, xnbr);
	count += ft_tester('x', "%#.*x", 5, xnbr);
	count += ft_tester('x', "%#.*x", -5, xnbr);
	count += ft_tester('x', "%0*.*x", 8, 5, xnbr);
	count += ft_tester('x', "%0*.*x", -8, 5, xnbr);
	count += ft_tester('x', "%0*.*x", 8, -5, xnbr);
	count += ft_tester('x', "%0*.*x", -8, -5, xnbr);
	count += ft_tester('x', "%-*.*x", 8, 5, xnbr);
	count += ft_tester('x', "%-*.*x", -8, 5, xnbr);
	count += ft_tester('x', "%#*.*x", 8, 5, xnbr);
	count += ft_tester('x', "%#*.*x", -8, 5, xnbr);
	count += ft_tester('x', "%#*.*x", 8, 0, 0u);
	count += ft_tester('x', "%#*.*x", -8, 0, 0u);
	count += ft_tester('x', "%#*.*x", 8, -5, xnbr);
	count += ft_tester('x', "%#*.*x", -8, -5, xnbr);
	count += ft_tester('x', "%+x", xnbr);
	count += ft_tester('x', "%+x", 0u);
	count += ft_tester('x', "%+5x", xnbr);
	count += ft_tester('x', "%+05x", xnbr);
	count += ft_tester('x', "%+.5x", xnbr);
	count += ft_tester('x', "%+8.5x", xnbr);
	count += ft_tester('x', "% x", xnbr);
	count += ft_tester('x', "% x", 0u);
	count += ft_tester('x', "% 5x", xnbr);
	count += ft_tester('x', "% 05x", xnbr);
	count += ft_tester('x', "% .5x", xnbr);
	count += ft_tester('x', "% 8.5x", xnbr);
	count += ft_tester('x', "abc%xdef", xnbr);
	count += ft_tester('x', "abc%5xdef", xnbr);
	count += ft_tester('x', "abc%-5xdef", xnbr);
	count += ft_tester('x', "abc%05xdef", xnbr);
	count += ft_tester('x', "abc%#xdef", xnbr);
	count += ft_tester('x', "abc%#05xdef", xnbr);
	count += ft_tester('x', "abc%.5xdef", xnbr);
	count += ft_tester('x', "abc%8.5xdef", xnbr);
	count += ft_tester('x', "abc%#8.5xdef", xnbr);
	count += ft_tester('x', "abc%xdef", 0u);
	count += ft_tester('x', "abc%5.0xdef", 0u);
	count += ft_tester('x', "abc%#.0xdef", 0u);
	count += ft_tester('x', "%x%x", 42u, 255u);
	count += ft_tester('x', "%x %x", 42u, UINT_MAX);
	count += ft_tester('x', "%5x%5x", 42u, 255u);
	count += ft_tester('x', "%-5x%-5x", 42u, 255u);
	count += ft_tester('x', "%05x%05x", 42u, 255u);
	count += ft_tester('x', "%#x%#x", 42u, 255u);
	count += ft_tester('x', "%#05x%#05x", 42u, 255u);
	count += ft_tester('x', "%.5x%.5x", 42u, 255u);
	count += ft_tester('x', "%8.5x%8.5x", 42u, UINT_MAX);
	count += ft_tester('x', "%#8.5x%#8.5x", 42u, UINT_MAX);
	count += ft_tester('x', "%*x%*x", 5, 42u, 5, 255u);
	count += ft_tester('x', "%*x%*x", -5, 42u, -5, 255u);
	count += ft_tester('x', "%*.*x%*.*x", 8, 5, 42u, 8, 5, UINT_MAX);
	count += ft_tester('x', "%*.*x%*.*x", -8, 5, 42u, -8, 5, UINT_MAX);
	count += ft_tester('x', "%#*.*x%#*.*x", 8, 5, 42u, 8, 5, UINT_MAX);
	
	ft_putendl_fd("%x", 1);
	write(1, "SUCCED TESTS : ", 15);
	ft_putnbr_fd(count, 1);
	write(1, "\n", 1);
	write(1, "FAILED TESTS : ", 15);
	ft_putnbr_fd(257 - count, 1);
	write(1, "\n\n", 2);
	return ;
}
