/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_test_s.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: victor <victor.horel@learner.42.tech>      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/14 17:31:29 by victor            #+#    #+#             */
/*   Updated: 2026/05/16 08:40:35 by victor           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_tester.h"

void	ft_test_s(void)
{
	int		count;
	char	*str;
	
	count = 0;
	str = "Hello42";
	
	count += ft_tester('s', "%s", str);
	count += ft_tester('s', "%s", "");
	count += ft_tester('s', "%s", "a");
	count += ft_tester('s', "%s", "Hello");
	count += ft_tester('s', "%s", "Hello world");
	count += ft_tester('s', "%s", NULL);
	count += ft_tester('s', "%1s", str);
	count += ft_tester('s', "%2s", str);
	count += ft_tester('s', "%3s", str);
	count += ft_tester('s', "%5s", str);
	count += ft_tester('s', "%10s", str);
	count += ft_tester('s', "%20s", str);
	count += ft_tester('s', "%1s", "");
	count += ft_tester('s', "%5s", "");
	count += ft_tester('s', "%10s", "");
	count += ft_tester('s', "%1s", NULL);
	count += ft_tester('s', "%5s", NULL);
	count += ft_tester('s', "%10s", NULL);
	count += ft_tester('s', "%20s", NULL);
	count += ft_tester('s', "%-1s", str);
	count += ft_tester('s', "%-2s", str);
	count += ft_tester('s', "%-3s", str);
	count += ft_tester('s', "%-5s", str);
	count += ft_tester('s', "%-10s", str);
	count += ft_tester('s', "%-20s", str);
	count += ft_tester('s', "%-1s", "");
	count += ft_tester('s', "%-5s", "");
	count += ft_tester('s', "%-10s", "");
	count += ft_tester('s', "%-1s", NULL);
	count += ft_tester('s', "%-5s", NULL);
	count += ft_tester('s', "%-10s", NULL);
	count += ft_tester('s', "%-20s", NULL);
	count += ft_tester('s', "%.0s", str);
	count += ft_tester('s', "%.1s", str);
	count += ft_tester('s', "%.2s", str);
	count += ft_tester('s', "%.3s", str);
	count += ft_tester('s', "%.5s", str);
	count += ft_tester('s', "%.10s", str);
	count += ft_tester('s', "%.20s", str);
	count += ft_tester('s', "%.0s", "");
	count += ft_tester('s', "%.1s", "");
	count += ft_tester('s', "%.5s", "");
	count += ft_tester('s', "%.0s", "a");
	count += ft_tester('s', "%.1s", "a");
	count += ft_tester('s', "%.2s", "a");
	count += ft_tester('s', "%.0s", NULL);
	count += ft_tester('s', "%.1s", NULL);
	count += ft_tester('s', "%.2s", NULL);
	count += ft_tester('s', "%.3s", NULL);
	count += ft_tester('s', "%.5s", NULL);
	count += ft_tester('s', "%.6s", NULL);
	count += ft_tester('s', "%.10s", NULL);
	count += ft_tester('s', "%1.0s", str);
	count += ft_tester('s', "%1.1s", str);
	count += ft_tester('s', "%1.3s", str);
	count += ft_tester('s', "%5.0s", str);
	count += ft_tester('s', "%5.1s", str);
	count += ft_tester('s', "%5.2s", str);
	count += ft_tester('s', "%5.3s", str);
	count += ft_tester('s', "%5.5s", str);
	count += ft_tester('s', "%5.10s", str);
	count += ft_tester('s', "%10.0s", str);
	count += ft_tester('s', "%10.1s", str);
	count += ft_tester('s', "%10.3s", str);
	count += ft_tester('s', "%10.5s", str);
	count += ft_tester('s', "%10.10s", str);
	count += ft_tester('s', "%10.20s", str);
	count += ft_tester('s', "%20.0s", str);
	count += ft_tester('s', "%20.3s", str);
	count += ft_tester('s', "%20.10s", str);
	count += ft_tester('s', "%5.0s", "");
	count += ft_tester('s', "%5.3s", "");
	count += ft_tester('s', "%10.0s", "");
	count += ft_tester('s', "%10.3s", "");
	count += ft_tester('s', "%5.0s", NULL);
	count += ft_tester('s', "%5.1s", NULL);
	count += ft_tester('s', "%5.3s", NULL);
	count += ft_tester('s', "%5.6s", NULL);
	count += ft_tester('s', "%10.0s", NULL);
	count += ft_tester('s', "%10.3s", NULL);
	count += ft_tester('s', "%10.6s", NULL);
	count += ft_tester('s', "%10.10s", NULL);
	count += ft_tester('s', "%-1.0s", str);
	count += ft_tester('s', "%-1.1s", str);
	count += ft_tester('s', "%-1.3s", str);
	count += ft_tester('s', "%-5.0s", str);
	count += ft_tester('s', "%-5.1s", str);
	count += ft_tester('s', "%-5.2s", str);
	count += ft_tester('s', "%-5.3s", str);
	count += ft_tester('s', "%-5.5s", str);
	count += ft_tester('s', "%-5.10s", str);
	count += ft_tester('s', "%-10.0s", str);
	count += ft_tester('s', "%-10.1s", str);
	count += ft_tester('s', "%-10.3s", str);
	count += ft_tester('s', "%-10.5s", str);
	count += ft_tester('s', "%-10.10s", str);
	count += ft_tester('s', "%-10.20s", str);
	count += ft_tester('s', "%-20.0s", str);
	count += ft_tester('s', "%-20.3s", str);
	count += ft_tester('s', "%-20.10s", str);
	count += ft_tester('s', "%-5.0s", "");
	count += ft_tester('s', "%-5.3s", "");
	count += ft_tester('s', "%-10.0s", "");
	count += ft_tester('s', "%-10.3s", "");
	count += ft_tester('s', "%-5.0s", NULL);
	count += ft_tester('s', "%-5.1s", NULL);
	count += ft_tester('s', "%-5.3s", NULL);
	count += ft_tester('s', "%-5.6s", NULL);
	count += ft_tester('s', "%-10.0s", NULL);
	count += ft_tester('s', "%-10.3s", NULL);
	count += ft_tester('s', "%-10.6s", NULL);
	count += ft_tester('s', "%-10.10s", NULL);
	count += ft_tester('s', "%01s", str);
	count += ft_tester('s', "%02s", str);
	count += ft_tester('s', "%05s", str);
	count += ft_tester('s', "%010s", str);
	count += ft_tester('s', "%020s", str);
	count += ft_tester('s', "%05s", "");
	count += ft_tester('s', "%010s", "");
	count += ft_tester('s', "%05s", NULL);
	count += ft_tester('s', "%010s", NULL);
	count += ft_tester('s', "%-01s", str);
	count += ft_tester('s', "%-02s", str);
	count += ft_tester('s', "%-05s", str);
	count += ft_tester('s', "%-010s", str);
	count += ft_tester('s', "%-05s", "");
	count += ft_tester('s', "%-010s", "");
	count += ft_tester('s', "%-05s", NULL);
	count += ft_tester('s', "%-010s", NULL);
	count += ft_tester('s', "%--1s", str);
	count += ft_tester('s', "%--5s", str);
	count += ft_tester('s', "%---5s", str);
	count += ft_tester('s', "%0001s", str);
	count += ft_tester('s', "%0005s", str);
	count += ft_tester('s', "%00010s", str);
	count += ft_tester('s', "%--005s", str);
	count += ft_tester('s', "%-0-05s", str);
	count += ft_tester('s', "%*s", 0, str);
	count += ft_tester('s', "%*s", 1, str);
	count += ft_tester('s', "%*s", 2, str);
	count += ft_tester('s', "%*s", 5, str);
	count += ft_tester('s', "%*s", 10, str);
	count += ft_tester('s', "%*s", 20, str);
	count += ft_tester('s', "%*s", 0, "");
	count += ft_tester('s', "%*s", 5, "");
	count += ft_tester('s', "%*s", 10, "");
	count += ft_tester('s', "%*s", 0, NULL);
	count += ft_tester('s', "%*s", 5, NULL);
	count += ft_tester('s', "%*s", 10, NULL);
	count += ft_tester('s', "%*s", -1, str);
	count += ft_tester('s', "%*s", -2, str);
	count += ft_tester('s', "%*s", -5, str);
	count += ft_tester('s', "%*s", -10, str);
	count += ft_tester('s', "%*s", -20, str);
	count += ft_tester('s', "%*s", -5, "");
	count += ft_tester('s', "%*s", -10, "");
	count += ft_tester('s', "%*s", -5, NULL);
	count += ft_tester('s', "%*s", -10, NULL);
	count += ft_tester('s', "%.*s", 0, str);
	count += ft_tester('s', "%.*s", 1, str);
	count += ft_tester('s', "%.*s", 2, str);
	count += ft_tester('s', "%.*s", 3, str);
	count += ft_tester('s', "%.*s", 5, str);
	count += ft_tester('s', "%.*s", 10, str);
	count += ft_tester('s', "%.*s", 20, str);
	count += ft_tester('s', "%.*s", 0, "");
	count += ft_tester('s', "%.*s", 3, "");
	count += ft_tester('s', "%.*s", 10, "");
	count += ft_tester('s', "%.*s", 0, NULL);
	count += ft_tester('s', "%.*s", 1, NULL);
	count += ft_tester('s', "%.*s", 3, NULL);
	count += ft_tester('s', "%.*s", 6, NULL);
	count += ft_tester('s', "%.*s", 10, NULL);
	count += ft_tester('s', "%.*s", -1, str);
	count += ft_tester('s', "%.*s", -2, str);
	count += ft_tester('s', "%.*s", -5, str);
	count += ft_tester('s', "%.*s", -10, str);
	count += ft_tester('s', "%.*s", -5, "");
	count += ft_tester('s', "%.*s", -5, NULL);
	count += ft_tester('s', "%*.*s", 0, 0, str);
	count += ft_tester('s', "%*.*s", 0, 3, str);
	count += ft_tester('s', "%*.*s", 5, 0, str);
	count += ft_tester('s', "%*.*s", 5, 1, str);
	count += ft_tester('s', "%*.*s", 5, 3, str);
	count += ft_tester('s', "%*.*s", 5, 10, str);
	count += ft_tester('s', "%*.*s", 10, 0, str);
	count += ft_tester('s', "%*.*s", 10, 3, str);
	count += ft_tester('s', "%*.*s", 10, 10, str);
	count += ft_tester('s', "%*.*s", -5, 0, str);
	count += ft_tester('s', "%*.*s", -5, 1, str);
	count += ft_tester('s', "%*.*s", -5, 3, str);
	count += ft_tester('s', "%*.*s", -5, 10, str);
	count += ft_tester('s', "%*.*s", -10, 0, str);
	count += ft_tester('s', "%*.*s", -10, 3, str);
	count += ft_tester('s', "%*.*s", -10, 10, str);
	count += ft_tester('s', "%*.*s", 5, -1, str);
	count += ft_tester('s', "%*.*s", 5, -5, str);
	count += ft_tester('s', "%*.*s", 10, -1, str);
	count += ft_tester('s', "%*.*s", 10, -5, str);
	count += ft_tester('s', "%*.*s", -5, -1, str);
	count += ft_tester('s', "%*.*s", -5, -5, str);
	count += ft_tester('s', "%*.*s", -10, -1, str);
	count += ft_tester('s', "%*.*s", -10, -5, str);
	count += ft_tester('s', "%*.*s", 10, 3, "");
	count += ft_tester('s', "%*.*s", -10, 3, "");
	count += ft_tester('s', "%*.*s", 10, 0, "");
	count += ft_tester('s', "%*.*s", -10, 0, "");
	count += ft_tester('s', "%*.*s", 10, 3, NULL);
	count += ft_tester('s', "%*.*s", -10, 3, NULL);
	count += ft_tester('s', "%*.*s", 10, 6, NULL);
	count += ft_tester('s', "%*.*s", -10, 6, NULL);
	count += ft_tester('s', "%*.*s", 10, -3, NULL);
	count += ft_tester('s', "%*.*s", -10, -3, NULL);
	count += ft_tester('s', "%0*s", 0, str);
	count += ft_tester('s', "%0*s", 1, str);
	count += ft_tester('s', "%0*s", 5, str);
	count += ft_tester('s', "%0*s", 10, str);
	count += ft_tester('s', "%0*s", -5, str);
	count += ft_tester('s', "%0*s", -10, str);
	count += ft_tester('s', "%-*s", 0, str);
	count += ft_tester('s', "%-*s", 1, str);
	count += ft_tester('s', "%-*s", 5, str);
	count += ft_tester('s', "%-*s", 10, str);
	count += ft_tester('s', "%-*s", -5, str);
	count += ft_tester('s', "%-*s", -10, str);
	count += ft_tester('s', "%-0*s", 0, str);
	count += ft_tester('s', "%-0*s", 1, str);
	count += ft_tester('s', "%-0*s", 5, str);
	count += ft_tester('s', "%-0*s", 10, str);
	count += ft_tester('s', "%-0*s", -5, str);
	count += ft_tester('s', "%-0*s", -10, str);
	count += ft_tester('s', "abc%sdef", str);
	count += ft_tester('s', "abc%5sdef", str);
	count += ft_tester('s', "abc%-5sdef", str);
	count += ft_tester('s', "abc%.3sdef", str);
	count += ft_tester('s', "abc%10.3sdef", str);
	count += ft_tester('s', "abc%-10.3sdef", str);
	count += ft_tester('s', "abc%sdef", "");
	count += ft_tester('s', "abc%5sdef", "");
	count += ft_tester('s', "abc%-5sdef", "");
	count += ft_tester('s', "abc%sdef", NULL);
	count += ft_tester('s', "abc%5sdef", NULL);
	count += ft_tester('s', "abc%-5sdef", NULL);
	count += ft_tester('s', "abc%.3sdef", NULL);
	count += ft_tester('s', "abc%10.3sdef", NULL);
	count += ft_tester('s', "abc%-10.3sdef", NULL);
	count += ft_tester('s', "%s%s", "Hello", "World");
	count += ft_tester('s', "%s %s", "Hello", "World");
	count += ft_tester('s', "%5s%5s", "A", "B");
	count += ft_tester('s', "%-5s%-5s", "A", "B");
	count += ft_tester('s', "%10.3s%10.3s", "Hello", "World");
	count += ft_tester('s', "%-10.3s%-10.3s", "Hello", "World");
	count += ft_tester('s', "%*s%*s", 5, "A", 5, "B");
	count += ft_tester('s', "%*s%*s", -5, "A", -5, "B");
	count += ft_tester('s', "%*.*s%*.*s", 10, 3, "Hello", 10, 3, "World");
	count += ft_tester('s', "%*.*s%*.*s", -10, 3, "Hello", -10, 3, "World");
	count += ft_tester('s', "%s%s", "", "World");
	count += ft_tester('s', "%s%s", "Hello", "");
	count += ft_tester('s', "%s%s", "", "");
	count += ft_tester('s', "%s%s", NULL, "World");
	count += ft_tester('s', "%s%s", "Hello", NULL);
	count += ft_tester('s', "%s%s", NULL, NULL);

	ft_putendl_fd("%s", 1);
	write(1, "SUCCED TESTS : ", 15);
	ft_putnbr_fd(count, 1);
	write(1, "\n", 1);
	write(1, "FAILED TESTS : ", 15);
	ft_putnbr_fd(262 - count, 1);
	write(1, "\n\n", 2);
	return ;
}
