/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_test_p.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: victor <victor.horel@learner.42.tech>      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/14 17:39:27 by victor            #+#    #+#             */
/*   Updated: 2026/05/16 08:38:28 by victor           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_tester.h"

void	ft_test_p(void)
{
	int			count;
	void		*p;
	
	count = 0;
	p = &count;
	
	count += ft_tester('p', "%p", p);
	count += ft_tester('p', "%p", NULL);
	count += ft_tester('p', "%1p", p);
	count += ft_tester('p', "%2p", p);
	count += ft_tester('p', "%5p", p);
	count += ft_tester('p', "%10p", p);
	count += ft_tester('p', "%20p", p);
	count += ft_tester('p', "%30p", p);
	count += ft_tester('p', "%1p", NULL);
	count += ft_tester('p', "%2p", NULL);
	count += ft_tester('p', "%5p", NULL);
	count += ft_tester('p', "%10p", NULL);
	count += ft_tester('p', "%20p", NULL);
	count += ft_tester('p', "%30p", NULL);
	count += ft_tester('p', "%-1p", p);
	count += ft_tester('p', "%-2p", p);
	count += ft_tester('p', "%-5p", p);
	count += ft_tester('p', "%-10p", p);
	count += ft_tester('p', "%-20p", p);
	count += ft_tester('p', "%-30p", p);
	count += ft_tester('p', "%-1p", NULL);
	count += ft_tester('p', "%-2p", NULL);
	count += ft_tester('p', "%-5p", NULL);
	count += ft_tester('p', "%-10p", NULL);
	count += ft_tester('p', "%-20p", NULL);
	count += ft_tester('p', "%-30p", NULL);
	count += ft_tester('p', "%01p", p);
	count += ft_tester('p', "%02p", p);
	count += ft_tester('p', "%05p", p);
	count += ft_tester('p', "%010p", p);
	count += ft_tester('p', "%020p", p);
	count += ft_tester('p', "%01p", NULL);
	count += ft_tester('p', "%02p", NULL);
	count += ft_tester('p', "%05p", NULL);
	count += ft_tester('p', "%010p", NULL);
	count += ft_tester('p', "%020p", NULL);
	count += ft_tester('p', "%-01p", p);
	count += ft_tester('p', "%-02p", p);
	count += ft_tester('p', "%-05p", p);
	count += ft_tester('p', "%-010p", p);
	count += ft_tester('p', "%-020p", p);
	count += ft_tester('p', "%-01p", NULL);
	count += ft_tester('p', "%-02p", NULL);
	count += ft_tester('p', "%-05p", NULL);
	count += ft_tester('p', "%-010p", NULL);
	count += ft_tester('p', "%-020p", NULL);
	count += ft_tester('p', "%--1p", p);
	count += ft_tester('p', "%--5p", p);
	count += ft_tester('p', "%---5p", p);
	count += ft_tester('p', "%0001p", p);
	count += ft_tester('p', "%0005p", p);
	count += ft_tester('p', "%00010p", p);
	count += ft_tester('p', "%--005p", p);
	count += ft_tester('p', "%-0-05p", p);
	count += ft_tester('p', "%--1p", NULL);
	count += ft_tester('p', "%--5p", NULL);
	count += ft_tester('p', "%---5p", NULL);
	count += ft_tester('p', "%0001p", NULL);
	count += ft_tester('p', "%0005p", NULL);
	count += ft_tester('p', "%00010p", NULL);
	count += ft_tester('p', "%--005p", NULL);
	count += ft_tester('p', "%-0-05p", NULL);
	count += ft_tester('p', "%*p", 0, p);
	count += ft_tester('p', "%*p", 1, p);
	count += ft_tester('p', "%*p", 2, p);
	count += ft_tester('p', "%*p", 5, p);
	count += ft_tester('p', "%*p", 10, p);
	count += ft_tester('p', "%*p", 20, p);
	count += ft_tester('p', "%*p", 30, p);
	count += ft_tester('p', "%*p", 0, NULL);
	count += ft_tester('p', "%*p", 1, NULL);
	count += ft_tester('p', "%*p", 2, NULL);
	count += ft_tester('p', "%*p", 5, NULL);
	count += ft_tester('p', "%*p", 10, NULL);
	count += ft_tester('p', "%*p", 20, NULL);
	count += ft_tester('p', "%*p", 30, NULL);
	count += ft_tester('p', "%*p", -1, p);
	count += ft_tester('p', "%*p", -2, p);
	count += ft_tester('p', "%*p", -5, p);
	count += ft_tester('p', "%*p", -10, p);
	count += ft_tester('p', "%*p", -20, p);
	count += ft_tester('p', "%*p", -30, p);
	count += ft_tester('p', "%*p", -1, NULL);
	count += ft_tester('p', "%*p", -2, NULL);
	count += ft_tester('p', "%*p", -5, NULL);
	count += ft_tester('p', "%*p", -10, NULL);
	count += ft_tester('p', "%*p", -20, NULL);
	count += ft_tester('p', "%*p", -30, NULL);
	count += ft_tester('p', "%0*p", 0, p);
	count += ft_tester('p', "%0*p", 1, p);
	count += ft_tester('p', "%0*p", 5, p);
	count += ft_tester('p', "%0*p", 10, p);
	count += ft_tester('p', "%0*p", 20, p);
	count += ft_tester('p', "%0*p", -5, p);
	count += ft_tester('p', "%0*p", -10, p);
	count += ft_tester('p', "%0*p", 0, NULL);
	count += ft_tester('p', "%0*p", 1, NULL);
	count += ft_tester('p', "%0*p", 5, NULL);
	count += ft_tester('p', "%0*p", 10, NULL);
	count += ft_tester('p', "%0*p", 20, NULL);
	count += ft_tester('p', "%0*p", -5, NULL);
	count += ft_tester('p', "%0*p", -10, NULL);
	count += ft_tester('p', "%-*p", 0, p);
	count += ft_tester('p', "%-*p", 1, p);
	count += ft_tester('p', "%-*p", 5, p);
	count += ft_tester('p', "%-*p", 10, p);
	count += ft_tester('p', "%-*p", 20, p);
	count += ft_tester('p', "%-*p", -5, p);
	count += ft_tester('p', "%-*p", -10, p);
	count += ft_tester('p', "%-*p", 0, NULL);
	count += ft_tester('p', "%-*p", 1, NULL);
	count += ft_tester('p', "%-*p", 5, NULL);
	count += ft_tester('p', "%-*p", 10, NULL);
	count += ft_tester('p', "%-*p", 20, NULL);
	count += ft_tester('p', "%-*p", -5, NULL);
	count += ft_tester('p', "%-*p", -10, NULL);
	count += ft_tester('p', "%-0*p", 0, p);
	count += ft_tester('p', "%-0*p", 1, p);
	count += ft_tester('p', "%-0*p", 5, p);
	count += ft_tester('p', "%-0*p", 10, p);
	count += ft_tester('p', "%-0*p", 20, p);
	count += ft_tester('p', "%-0*p", -5, p);
	count += ft_tester('p', "%-0*p", -10, p);
	count += ft_tester('p', "%-0*p", 0, NULL);
	count += ft_tester('p', "%-0*p", 1, NULL);
	count += ft_tester('p', "%-0*p", 5, NULL);
	count += ft_tester('p', "%-0*p", 10, NULL);
	count += ft_tester('p', "%-0*p", 20, NULL);
	count += ft_tester('p', "%-0*p", -5, NULL);
	count += ft_tester('p', "%-0*p", -10, NULL);
	count += ft_tester('p', "%.0p", p);
	count += ft_tester('p', "%.1p", p);
	count += ft_tester('p', "%.3p", p);
	count += ft_tester('p', "%.5p", p);
	count += ft_tester('p', "%.10p", p);
	count += ft_tester('p', "%.0p", NULL);
	count += ft_tester('p', "%.1p", NULL);
	count += ft_tester('p', "%.3p", NULL);
	count += ft_tester('p', "%.5p", NULL);
	count += ft_tester('p', "%.10p", NULL);
	count += ft_tester('p', "%10.0p", p);
	count += ft_tester('p', "%10.1p", p);
	count += ft_tester('p', "%10.3p", p);
	count += ft_tester('p', "%10.5p", p);
	count += ft_tester('p', "%20.10p", p);
	count += ft_tester('p', "%10.0p", NULL);
	count += ft_tester('p', "%10.1p", NULL);
	count += ft_tester('p', "%10.3p", NULL);
	count += ft_tester('p', "%10.5p", NULL);
	count += ft_tester('p', "%20.10p", NULL);
	count += ft_tester('p', "%-10.0p", p);
	count += ft_tester('p', "%-10.1p", p);
	count += ft_tester('p', "%-10.3p", p);
	count += ft_tester('p', "%-10.5p", p);
	count += ft_tester('p', "%-20.10p", p);
	count += ft_tester('p', "%-10.0p", NULL);
	count += ft_tester('p', "%-10.1p", NULL);
	count += ft_tester('p', "%-10.3p", NULL);
	count += ft_tester('p', "%-10.5p", NULL);
	count += ft_tester('p', "%-20.10p", NULL);
	count += ft_tester('p', "%.*p", 0, p);
	count += ft_tester('p', "%.*p", 1, p);
	count += ft_tester('p', "%.*p", 3, p);
	count += ft_tester('p', "%.*p", 5, p);
	count += ft_tester('p', "%.*p", 10, p);
	count += ft_tester('p', "%.*p", -1, p);
	count += ft_tester('p', "%.*p", -5, p);
	count += ft_tester('p', "%.*p", 0, NULL);
	count += ft_tester('p', "%.*p", 1, NULL);
	count += ft_tester('p', "%.*p", 3, NULL);
	count += ft_tester('p', "%.*p", 5, NULL);
	count += ft_tester('p', "%.*p", 10, NULL);
	count += ft_tester('p', "%.*p", -1, NULL);
	count += ft_tester('p', "%.*p", -5, NULL);
	count += ft_tester('p', "%*.*p", 10, 0, p);
	count += ft_tester('p', "%*.*p", 10, 1, p);
	count += ft_tester('p', "%*.*p", 10, 5, p);
	count += ft_tester('p', "%*.*p", 20, 10, p);
	count += ft_tester('p', "%*.*p", -10, 0, p);
	count += ft_tester('p', "%*.*p", -10, 1, p);
	count += ft_tester('p', "%*.*p", -10, 5, p);
	count += ft_tester('p', "%*.*p", -20, 10, p);
	count += ft_tester('p', "%*.*p", 10, -1, p);
	count += ft_tester('p', "%*.*p", 10, -5, p);
	count += ft_tester('p', "%*.*p", -10, -1, p);
	count += ft_tester('p', "%*.*p", -10, -5, p);
	count += ft_tester('p', "%*.*p", 10, 0, NULL);
	count += ft_tester('p', "%*.*p", 10, 1, NULL);
	count += ft_tester('p', "%*.*p", 10, 5, NULL);
	count += ft_tester('p', "%*.*p", 20, 10, NULL);
	count += ft_tester('p', "%*.*p", -10, 0, NULL);
	count += ft_tester('p', "%*.*p", -10, 1, NULL);
	count += ft_tester('p', "%*.*p", -10, 5, NULL);
	count += ft_tester('p', "%*.*p", -20, 10, NULL);
	count += ft_tester('p', "%*.*p", 10, -1, NULL);
	count += ft_tester('p', "%*.*p", 10, -5, NULL);
	count += ft_tester('p', "%*.*p", -10, -1, NULL);
	count += ft_tester('p', "%*.*p", -10, -5, NULL);
	count += ft_tester('p', "abc%pdef", p);
	count += ft_tester('p', "abc%10pdef", p);
	count += ft_tester('p', "abc%-10pdef", p);
	count += ft_tester('p', "abc%20pdef", p);
	count += ft_tester('p', "abc%-20pdef", p);
	count += ft_tester('p', "abc%pdef", NULL);
	count += ft_tester('p', "abc%10pdef", NULL);
	count += ft_tester('p', "abc%-10pdef", NULL);
	count += ft_tester('p', "abc%20pdef", NULL);
	count += ft_tester('p', "abc%-20pdef", NULL);
	count += ft_tester('p', "%p%p", p, p);
	count += ft_tester('p', "%p %p", p, p);
	count += ft_tester('p', "%10p%10p", p, p);
	count += ft_tester('p', "%-10p%-10p", p, p);
	count += ft_tester('p', "%20p%20p", p, p);
	count += ft_tester('p', "%-20p%-20p", p, p);
	count += ft_tester('p', "%p%p", NULL, p);
	count += ft_tester('p', "%p%p", p, NULL);
	count += ft_tester('p', "%p%p", NULL, NULL);
	count += ft_tester('p', "%20p%20p", NULL, p);
	count += ft_tester('p', "%20p%20p", p, NULL);
	count += ft_tester('p', "%20p%20p", NULL, NULL);

	ft_putendl_fd("%p", 1);
	write(1, "SUCCED TESTS : ", 15);
	ft_putnbr_fd(count, 1);
	write(1, "\n", 1);
	write(1, "FAILED TESTS : ", 15);
	ft_putnbr_fd(220 - count, 1);
	write(1, "\n\n", 2);
	return ;
}
